config/routes.rb
Project::Application.routes.draw do
  resources :transactions
  resources :accounts
  root :to=> 'accounts#index'
  get "others/search"
  get "others/assign"
  devise_for :users
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :role_required

  def search
    @accounts = Account.all
    @amount = params[:amount]
    @f_account = params[:f_account]
    @t_account = params[:t_account]
    @t_date = params[:t_date]
    @transactions = Transaction.search(@amount,@f_account, @t_account, @t_date)
    
      
  end

 def assign
   @roles = Role.all
   @users = User.all
   @assigned_user = params[:user]
   @assigned_role = params[:role]
   if @assigned_user != "" and @assigned_role != "" and @assigned_user and @assigned_role 
       user = User.find_by_id(@assigned_user)
       user.update( role: Role.find_by_id(@assigned_role))
       flash.now[:notice] = 'The user has been authorized!'
   else
	flash.now[:error] = 'Error occured, make sure that you select the user and role'
   end


 
 end
end

app/helpers/others_helper.rb
module OthersHelper
end

app/views/others/assign.html.erb
<h1>User Management</h1>
<%=form_tag others_assign_path, :method => 'get' do %>
  <p>
    User
    <%= select_tag :user, options_from_collection_for_select(@users,:id,:email), :include_blank => true, :class => 'dropdown-toggle' %>
    Role
    <%= select_tag :role, options_from_collection_for_select(@roles,:id,:name), :include_blank => true, :class => 'dropdown-toggle' %>
    <p>
    <%= submit_tag "Assign User", :name => nil, :class => 'btn btn-primary' %>
    </p>
  </p>
<% end %>

<p>
</p>
<p>
</p>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>User Email</th>
      <th>Current Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
	<td><%= user.email %></td>
        <td><% Role.where(:id => user.role_id).each do |role| %> 
             <%= role.name%>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/others/search.html.erb
<h1>Transactions Search</h1>
<%=form_tag others_search_path, :method => 'get' do %>
  <p>
    Date
    <%= date_field_tag :t_date %>
    Amount
    <%= text_field_tag :amount %>
    From Account
    <%= select_tag :f_account, options_from_collection_for_select(@accounts,:id,:a_name), :include_blank => true %>
    To Account
    <%= select_tag :t_account, options_from_collection_for_select(@accounts,:id,:a_name), :include_blank => true %>
    <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
  </p>
<% end %>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>From Account</th>
      <th>To Account</th>
      <th>Transaction Amount</th>
      <th>Transaction Date</th>
      <th>Transaction Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><% Account.where(:id => transaction.from_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><% Account.where(:id => transaction.to_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><%= transaction.t_amount %></td>
        <td><%= transaction.t_date %></td>
        <td><%= transaction.t_desc %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%#= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>