config/routes.rb
Project::Application.routes.draw do
  resources :transactions
  resources :accounts
  root :to=> 'accounts#index'
  get "others/search"
  get "others/assign"
  devise_for :users
end

app/views/pages/assign.html.erb
<h1>User assignment</h1>
<p>
<%= link_to 'Home Page', accounts_path %>
</p>

<%=form_tag assign_path, :method => 'get' do %>
  <p>
    User
    <%= select_tag :user, options_from_collection_for_select(@users,:id,:email), :include_blank => true %>
    Role
    <%= select_tag :role, options_from_collection_for_select(@roles,:id,:name), :include_blank => true %>
    <p>
    <%= submit_tag "Assign", :name => nil %>
    </p>
  </p>
<% end %>

<% if flash[:notice] %>
   <div class="notice"><%= flash[:notice] %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th>User Email</th>
      <th>Current Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
	<td><%= user.email %></td>
        <td><% Role.where(:id => user.role_id).each do |role| %> 
             <%= role.name%>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/search.html.erb
<h1>Transactions Search</h1>
<%=form_tag search_path, :method => 'get' do %>
  <p>
    Date
    <%= date_field_tag :t_date %>
    Amount
    <%= text_field_tag :amount %>
    From Account
    <%= select_tag :f_account, options_from_collection_for_select(@accounts,:id,:a_name), :include_blank => true %>
    To Account
    <%= select_tag :t_account, options_from_collection_for_select(@accounts,:id,:a_name), :include_blank => true %>
    <p>
    <%= submit_tag "Search", :name => nil %>
    </p>
  </p>
<% end %>

<p>
<%= link_to 'Home Page', accounts_path %>
</p>
<table>
  <thead>
    <tr>
      <th>From Account</th>
      <th>To Account</th>
      <th>Transaction Amount</th>
      <th>Transaction Date</th>
      <th>Transaction Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><% Account.where(:id => transaction.from_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><% Account.where(:id => transaction.to_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><%= transaction.t_amount %></td>
        <td><%= transaction.t_date %></td>
        <td><%= transaction.t_desc %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%#= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>