config/routes.rb
Project::Application.routes.draw do
  resources :transactions
  resources :accounts
  root :to=> 'accounts#index'
  get "others/search"
  get "others/assign"
  devise_for :users
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :role_required,  except: [:index]
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    @sort = nil
    if params.has_key?(:sort)
      @sort = params[:sort]
      if @sort == 'fname'
	@transactions = Transaction.order("from_account_id")
      elsif @sort == 'tname'
        @transactions = Transaction.order("to_account_id")
      elsif @sort == 'amount'
        @transactions = Transaction.order("t_amount")
      elsif @sort == 'date'
        @transactions = Transaction.order("t_date")
      else
        @transactions = Transaction.all
      end
    end

  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
   
 
    respond_to do |format|
		if @transaction.save
			format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
			format.json { render action: 'show', status: :created, location: @transaction }
		else
			format.html { render action: 'new' }
			format.json { render json: @transaction.errors, status: :unprocessable_entity }
		end
	end
     
	if transaction_params[:t_amount].to_f > 0
	    from_account = Account.find_by_id(transaction_params[:from_account_id])
		to_account = Account.find_by_id(transaction_params[:to_account_id])
   	    #account_from.a_amount = account_from.a_amount - transaction_params[:t_amount].to_f
	    from_account_type = Account.find_by_id(transaction_params[:from_account_id]).a_type
	    
		if from_account_type == "Liability"
			from_account.a_amount += transaction_params[:t_amount].to_f
			to_account.a_amount += transaction_params[:t_amount].to_f
		else
			if from_account.a_amount >= 0
				from_account.a_amount -= transaction_params[:t_amount].to_f
				to_account.a_amount += transaction_params[:t_amount].to_f
				
			end
		end
		
		from_account.save
		to_account.save
   
	end
  end

    
  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update

    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end

    if transaction_params[:t_amount].to_f > 0
	   #current_transaction = Transaction.find_by_id(transaction_params[:id])
	   #p current_transaction.to_s + "IIIIIIIIIIIIIIIIIIIIIIIIIII"
	   #p self.find_by_id (transaction_params[:id]).t_amount
	   account_from = Account.find_by_id(transaction_params[:from_account_id])
	   #p @transaction.t_amount.to_s + "IIIIIIIIIIIIIIIIIII"
	   #p transaction_params[:t_amount].to_s 
   	   account_from.a_amount = account_from.a_amount + @transaction.t_amount - transaction_params[:t_amount].to_f
	   #p account_from.a_amount
	   if account_from.a_amount >= 0
        	account_from.save
        	account_to = Account.find_by_id(transaction_params[:to_account_id])
        	account_to.a_amount = account_to.a_amount - @transaction.t_amount + transaction_params[:t_amount].to_f
        	account_to.save
   	   end
    end
 
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from_account_id, :to_account_id, :t_amount, :t_date, :t_desc, :t_attac)
      #, :t_attach_file_name, :t_attach_content_type, :t_attach_file_size, :t_attach_updated_at)
      #params.require(:transaction).permit(:t_attach)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for @transaction, :html => { :multipart => true } do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_account_id %><br>
    <% if @transaction.from_account_id != nil %>
      <%= f.collection_select :from_account_id, Account.where("id = " + @transaction.from_account_id.to_s), :id, :a_name, :class => 'dropdown-toggle' %>
    <% else %>
      <%= f.collection_select :from_account_id, Account.all, :id, :a_name, :prompt => "Select a prospect", :class => 'dropdown-toggle'%>
    <% end %> 
  </div>
  <div class="field">
    <%= f.label :to_account_id %><br>
    <% if @transaction.to_account_id != nil %>
      <%= f.collection_select :to_account_id, Account.where("id = " + @transaction.to_account_id.to_s), :id, :a_name, :class => 'dropdown-toggle' %>
    <% else %>
      <%= f.collection_select :to_account_id, Account.all, :id, :a_name, :prompt => "Select a prospect", :class => 'dropdown-toggle' %>
    <% end %> 
  </div>
  <div class="field">
    <%= f.label "Amount" %><br>
    <%= f.text_field :t_amount, :class => 'text_field' %>
  </div>
  <div class="field">
    <%= f.label "Date" %><br>
    <%= f.date_select :t_date, :class => 'text_field' %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_area :t_desc, :class => 'text_field' %>
  </div>
  <div class="field">
    <%= f.label "Attachment" %><br>
    <%= f.file_field :t_attac , :class => 'btn btn-primary'%>
  </div>
   <p>
   </p>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                transactions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Transactions List</h1>
<table class="table table-responsive">
  <thead>
    <tr>
      <th><%=link_to 'From Account', sort: :fname %></th>
      <th><%=link_to 'To Account', sort: :tname %></th>
      <th><%=link_to 'Transaction Amount', sort: :amount %></th>
      <th><%=link_to 'Transaction Date', sort: :date %></th>
      <th>Transaction Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><% Account.where(:id => transaction.from_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><% Account.where(:id => transaction.to_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><%= transaction.t_amount %></td>
        <td><%= transaction.t_date %></td>
        <td><%= transaction.t_desc %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%#= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>
<p>
<%= link_to 'Search Transactions', others_search_path, method: :get %>
</p>

<html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Amount');
	<% @amount_by_day = Transaction.group(:t_date).select("t_date AS transaction_date", "sum(t_amount) as amount_sum") %>

        <% @amount_by_day.each do |transactions| %>
        	data.addRow(["<%= transactions.transaction_date %>", <%= transactions.amount_sum %>]);
	<% end %>

        var options = {
          title: 'Amount of transactions per day',
          vAxis: {title: 'Day',  titleTextStyle: {color: 'red'}}
        };

        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
  </body>
</html>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/search.html.erb
<h1>Transactions Search</h1>

<p>
<%= link_to 'Home Page', accounts_path %>
</p>
<table>
  <thead>
    <tr>
      <th><%=link_to 'From Account', sort: :fname %></th>
      <th><%=link_to 'To Account', sort: :tname %></th>
      <th><%=link_to 'Transaction Amount', sort: :amount %></th>
      <th><%=link_to 'Transaction Date', sort: :date %></th>
      <th>Transaction Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><% Account.where(:id => transaction.from_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><% Account.where(:id => transaction.to_account_id).each do |account| %> 
             <%= account.a_name%>
            <% end %>
        </td>
        <td><%= transaction.t_amount %></td>
        <td><%= transaction.t_date %></td>
        <td><%= transaction.t_desc %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%#= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/show.html.erb
<h1>Information</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>From Account:</strong>
  <%#= @transaction.from_account_id %>
  <% Account.where(:id => @transaction.from_account_id).each do |account| %> 
   <tr>
     <td width="10"><%= account.a_name%></td>
   </tr>
  <% end %>
</p>

<p>
  <strong>To Account:</strong>
  <%#= @transaction.to_account_id %>
  <% Account.where(:id => @transaction.to_account_id).each do |account| %> 
   <tr>
     <td width="10"><%= account.a_name%></td>
   </tr>
  <% end %>
</p>

<p>
  <strong>Transaction Amount:</strong>
  <%= @transaction.t_amount %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction.t_date %>
</p>

<p>
  <strong>Transaction desciption:</strong>
  <%= @transaction.t_desc %>
</p>
<p>
  <%= image_tag @transaction.t_attac.url(:medium) %>
</p>
<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>