config/routes.rb
Project::Application.routes.draw do
  resources :transactions
  resources :accounts
  root :to=> 'accounts#index'
  get "others/search"
  get "others/assign"
  devise_for :users
end

app/models/account.rb
class Account < ActiveRecord::Base

validates :a_amount, numericality: { greater_than_or_equal_to: 0 }
def self.search(search)
  if search
    find(:all, :conditions => ['a_name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :role_required,  except: [:index]

  #before_action :set_page,       only: [:edit, :update, :destroy]
  #before_action :owner_required, only: [:edit, :update, :destroy]

  def index 
    @accounts = Account.all
    @sort = nil
    if params.has_key?(:sort)
      @sort = params[:sort]
      if @sort == 'name'
	@accounts = Account.order("a_name")
      elsif @sort == 'type'
        @accounts = Account.order("a_type")
      elsif @sort == 'amount'
        @accounts = Account.order("a_amount")
      else
        @accounts = Account.all
      end
    end
    if params.has_key?(:search)
	@accounts = Account.search(params[:search])
    end


  end

  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:a_name, :a_type, :a_amount)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%#= Account.all %>
  <div class="field">
    <%= f.label "Account Name", :class => 'control-label' %><br>
    <%= f.text_field :a_name, :class => 'text_field' %>
  </div>
  <div class="field">
    <%= f.label "Account Type", :class => 'control-label' %><br>
    <%= f.select :a_type, ['Expense','Liability','Asset','Equity'], :class => 'dropdown-toggle' %>
  </div>
  <div class="field">
    <%= f.label "Amount", :class => 'control-label' %><br>
    <%= f.text_field :a_amount, :class => 'text_field' %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Accounts Balance</h1>

<label class='control-label'>
   Current User is < <%=current_user.email%> >
</label>
<p>
</P>
<%=form_tag accounts_path, :method => 'get' do %>
  <p>Account Name
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :a_name => nil, :class => 'btn btn-primary' %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%=link_to 'Account Name', sort: :name %></th>
      <th><%=link_to 'Account Type', sort: :type %></th>
      <th><%=link_to 'Account Amount', sort: :amount %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.a_name %></td>
        <td><%= account.a_type %></td>
        <td><%= account.a_amount %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
    
      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Account');
        data.addColumn('number', 'Amount');
        <% @accounts.each do |account| %>
        	data.addRow(["<%= account.a_name %>", <%= account.a_amount %>]);
	<% end %>
        

        // Set chart options
        var options = {'title':'Accounts balance distribution',
                       'width':600,
                       'height':500,
			is3D: true};
        

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>

<p>
<%= link_to 'New Account', new_account_path, :class => 'btn-link'%>
</p>
<p>
<%= link_to 'New Transaction', new_transaction_path, :class => 'btn-link' %>
</p>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1>Information</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Account Name:</strong>
  <%= @account.a_name %>
</p>

<p>
  <strong>Account Type:</strong>
  <%= @account.a_type %>
</p>

<p>
  <strong>Account Amount:</strong>
  <%= @account.a_amount %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>